Repository googleapis/nodejs-bigquery-connection, pull requests merged in 2020-07, with the labels that each got.

#7 build: update list of ignored links
  linkinator.config.json
  synth.metadata
Labels: cla: yes, context: none

#9 build: use bazel build
  package.json
  src/v1/connection_service_client.ts
  src/v1/connection_service_client_config.json
  synth.metadata
  synth.py
  test/gapic_connection_service_v1.ts
Labels: cla: yes

#17 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#16 chore: update samples package.json name
  package.json
  samples/package.json
Labels: cla: yes

#22 build: fix typo in publish
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#25 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes
