Repository googleapis/nodejs-bigquery-connection, pull requests merged in 2020-11, with the labels that each got.

#45 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full

#46 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/connection_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: bigqueryconnection, automerge, cla: yes

#48 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/connection_service_client.ts
  synth.metadata
Labels: api: bigqueryconnection, cla: yes, context: none

#50 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: bigqueryconnection, automerge, cla: yes, context: full
